### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by p-brz** [novacrazy/function_traits#3]
What is the project's license?

**Comment by novacrazy** [comment]
Effectively public domain, unlicensed.

**Comment by novacrazy** [comment]
Actually, the original repo that I took the file from and fixed things up is apparently under the Boost 1.0 license, but these are mostly derivative from the standard library stuff anyway. It really doesn't matter.

**Comment by p-brz** [comment]
Nice!

So i suggest using 'unlicense' to explicit states that it is public domain.

See pull request #4
